package sk.upjs.ics.swib.gui;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.List;
import sk.upjs.ics.swib.dao.KlientDao;
import sk.upjs.ics.swib.entity.Bonus;
import sk.upjs.ics.swib.entity.Klient;
import sk.upjs.ics.swib.entity.Uver;
import sk.upjs.ics.swib.exceptions.NieJeMozneSplacat;
import sk.upjs.ics.swib.factory.DaoFactory;
import sk.upjs.ics.swib.logic.KonstantyPreKlienta;
import sk.upjs.ics.swib.logic.OfiCalculator;

/**
 *
 * @author Johnny
 */
public class JDVypocitajUver extends javax.swing.JDialog {

    private final UverComboBoxModel uverComboBoxModel = new UverComboBoxModel();
    private final KlientDao databazovyKlientDao = DaoFactory.INSTANCE.klientDao();
    private Klient klient;

    private Uver vybranyUver = null;

    /**
     * Creates new form JDVypocitajUver
     *
     * @param parent
     * @param modal
     */
    public JDVypocitajUver(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jcombZoznamUverov.setModel(uverComboBoxModel);
        jtfPMP.setText("0");                
    }

    public JDVypocitajUver(java.awt.Frame parent, Klient klient) {        
        this(parent, true);        
        this.klient = klient;
        setTitle("Vypočítaj úver • " + klient.getMeno() + " " + klient.getPriezvisko());
        jtfPMP.setText(databazovyKlientDao.priemernyMesacnyPrijem(klient).setScale(2, RoundingMode.DOWN).toString());
        jtfPMPU.setText(databazovyKlientDao.mozeNaMesiacMaximalneSplacat(klient).setScale(2, RoundingMode.DOWN).toString());
        jtfPMZ.setText(databazovyKlientDao.priemernyMesacnyZostatok(klient).setScale(2, RoundingMode.DOWN).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPocitaj = new javax.swing.JButton();
        btnStorno = new javax.swing.JButton();
        lblVyskaInychNakladov = new javax.swing.JLabel();
        lblVyskaUveru = new javax.swing.JLabel();
        lblPocetMesiacov = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaInfo = new javax.swing.JTextArea();
        jcbManzelka = new javax.swing.JCheckBox();
        lblPocetDeti = new javax.swing.JLabel();
        jtfPMPU = new javax.swing.JTextField();
        jtfPMP = new javax.swing.JTextField();
        jtfPMZ = new javax.swing.JTextField();
        lblPMPU = new javax.swing.JLabel();
        lblPMP = new javax.swing.JLabel();
        lblPMZ = new javax.swing.JLabel();
        jcombZoznamUverov = new javax.swing.JComboBox();
        jspPocetDeti = new javax.swing.JSpinner();
        jtfPMPUpraveny = new javax.swing.JTextField();
        btnVyplnUpraveny = new javax.swing.JButton();
        jsVyskaUveru = new javax.swing.JSpinner();
        jsPocetMesiacov = new javax.swing.JSpinner();
        jsVyskaInychNakladov = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        btnPocitaj.setText("Počítaj");
        btnPocitaj.setEnabled(false);
        btnPocitaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPocitajActionPerformed(evt);
            }
        });

        btnStorno.setText("Storno");
        btnStorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStornoActionPerformed(evt);
            }
        });

        lblVyskaInychNakladov.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblVyskaInychNakladov.setText("Výška iných nákladov (mesačne):");

        lblVyskaUveru.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblVyskaUveru.setText("Výška úveru:");

        lblPocetMesiacov.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPocetMesiacov.setText("Počet mesiacov:");

        jtaInfo.setColumns(20);
        jtaInfo.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jtaInfo.setRows(5);
        jtaInfo.setEnabled(false);
        jScrollPane1.setViewportView(jtaInfo);

        jcbManzelka.setText("Manželka");

        lblPocetDeti.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPocetDeti.setText("Počet detí:");

        jtfPMPU.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfPMPU.setText("0");
        jtfPMPU.setEnabled(false);

        jtfPMP.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfPMP.setText("0");
        jtfPMP.setEnabled(false);

        jtfPMZ.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfPMZ.setText("0");
        jtfPMZ.setEnabled(false);

        lblPMPU.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPMPU.setText("Priemerná mesačná bilancia:");

        lblPMP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPMP.setText("Priemerný mesačný príjem:");

        lblPMZ.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPMZ.setText("Priemerný meačný zostatok:");

        jcombZoznamUverov.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcombZoznamUverov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcombZoznamUverovActionPerformed(evt);
            }
        });

        jspPocetDeti.setModel(new javax.swing.SpinnerNumberModel());

        jtfPMPUpraveny.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfPMPUpraveny.setText("0");
        jtfPMPUpraveny.setEnabled(false);

        btnVyplnUpraveny.setText("Upravený úbytok");
        btnVyplnUpraveny.setEnabled(false);
        btnVyplnUpraveny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVyplnUpravenyActionPerformed(evt);
            }
        });

        jsVyskaUveru.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(1.0d), Double.valueOf(1.0d), null, Double.valueOf(0.010000000000000009d)));

        jsPocetMesiacov.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        jsVyskaInychNakladov.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), null, null, Double.valueOf(0.01d)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblVyskaInychNakladov)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jsVyskaInychNakladov)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblPMZ)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblPMPU)
                                            .addComponent(lblPMP))
                                        .addGap(5, 5, 5))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnVyplnUpraveny)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jcbManzelka)
                                .addGap(18, 18, 18)
                                .addComponent(lblPocetDeti)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcombZoznamUverov, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPocetMesiacov)
                                    .addComponent(lblVyskaUveru))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jsVyskaUveru, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                    .addComponent(jsPocetMesiacov))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnPocitaj)
                            .addGap(5, 5, 5)
                            .addComponent(btnStorno))
                        .addComponent(jtfPMPU, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jtfPMP, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jtfPMZ, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jtfPMPUpraveny))
                    .addComponent(jspPocetDeti, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVyskaInychNakladov)
                    .addComponent(jcbManzelka)
                    .addComponent(jspPocetDeti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPocetDeti)
                    .addComponent(jsVyskaInychNakladov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcombZoznamUverov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblVyskaUveru)
                    .addComponent(jsVyskaUveru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPocetMesiacov)
                    .addComponent(jsPocetMesiacov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPMPU)
                            .addComponent(jtfPMPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPMP)
                            .addComponent(jtfPMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfPMZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPMZ))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfPMPUpraveny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVyplnUpraveny))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPocitaj)
                            .addComponent(btnStorno)))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStornoActionPerformed
        dispose();
    }//GEN-LAST:event_btnStornoActionPerformed

    private void jcombZoznamUverovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcombZoznamUverovActionPerformed
        vybranyUver = uverComboBoxModel.getUver(jcombZoznamUverov.getSelectedIndex());
        btnVyplnUpraveny.setEnabled(true);
        if (((double)jsVyskaUveru.getValue()) != 0){
            btnPocitaj.setEnabled(true);
        }
    }//GEN-LAST:event_jcombZoznamUverovActionPerformed

    private void btnVyplnUpravenyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVyplnUpravenyActionPerformed
        vyplnPMPUpraveny();
    }//GEN-LAST:event_btnVyplnUpravenyActionPerformed

    private void btnPocitajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPocitajActionPerformed
        OfiCalculator ofiCalculator = new OfiCalculator();        
        double vyskaUveru = (double) jsVyskaUveru.getValue();
        int pocetMesiacov = (int) jsPocetMesiacov.getValue();
        int pocetDeti = (int) jspPocetDeti.getValue();
        KonstantyPreKlienta konstantyPreKlienta = new KonstantyPreKlienta(new BigDecimal(vyskaUveru), new BigDecimal(jtfPMP.getText()), new BigDecimal(jtfPMPU.getText()), pocetMesiacov, pocetDeti, vybranyUver.getBonusNaDieta(), vybranyUver.getBonusNaManzelku(), new BigDecimal(jtfPMZ.getText()));
        List<Bonus> bonusy = DaoFactory.INSTANCE.bonusDao().dajVsetky(vybranyUver);
        try{
            BigDecimal mesacnaUS = ofiCalculator.mesacnaUrokovaSadzba(konstantyPreKlienta, bonusy);
            jtaInfo.setText("Úver povolený:\n"+
                    "Výška úveru: " + vyskaUveru + "\n" +
                    "Mesačná splátka: " + mesacnaUS.setScale(2, RoundingMode.DOWN));
        } catch (NieJeMozneSplacat e){
            jtaInfo.setText("Nie je možné splácať tento úver");
        }
    }//GEN-LAST:event_btnPocitajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDVypocitajUver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDVypocitajUver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDVypocitajUver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDVypocitajUver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        /* zerem parky na ranajky
         * mozem kaslat paradajky
         * zerem buchty plne maku
         * ponuknem aj tvoju mamku
         * zerem salam buchty syry
         * uz ti isto tecu sliny
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDVypocitajUver dialog = new JDVypocitajUver(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPocitaj;
    private javax.swing.JButton btnStorno;
    private javax.swing.JButton btnVyplnUpraveny;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jcbManzelka;
    private javax.swing.JComboBox jcombZoznamUverov;
    private javax.swing.JSpinner jsPocetMesiacov;
    private javax.swing.JSpinner jsVyskaInychNakladov;
    private javax.swing.JSpinner jsVyskaUveru;
    private javax.swing.JSpinner jspPocetDeti;
    private javax.swing.JTextArea jtaInfo;
    private javax.swing.JTextField jtfPMP;
    private javax.swing.JTextField jtfPMPU;
    private javax.swing.JTextField jtfPMPUpraveny;
    private javax.swing.JTextField jtfPMZ;
    private javax.swing.JLabel lblPMP;
    private javax.swing.JLabel lblPMPU;
    private javax.swing.JLabel lblPMZ;
    private javax.swing.JLabel lblPocetDeti;
    private javax.swing.JLabel lblPocetMesiacov;
    private javax.swing.JLabel lblVyskaInychNakladov;
    private javax.swing.JLabel lblVyskaUveru;
    // End of variables declaration//GEN-END:variables

    private void vyplnPMPUpraveny() {
        if (vybranyUver != null) {
            int manzelka = 0;
            if (jcbManzelka.isSelected()) {
                manzelka = 1;
            }
            BigDecimal pmp = new BigDecimal(jtfPMPU.getText());
            double hodnota = pmp.doubleValue() - manzelka * vybranyUver.getBonusNaManzelku().doubleValue() 
                    - ((double) jsVyskaInychNakladov.getValue()) 
                    - ((int) jspPocetDeti.getValue()) * vybranyUver.getBonusNaDieta().doubleValue();
            jtfPMPUpraveny.setText(hodnota + "");
        }
    }
}
