package sk.upjs.ics.swib.gui;

import java.awt.event.KeyEvent;
import sk.upjs.ics.swib.entity.Klient;

/**
 *
 * @author Johnny
 */
public class JFZoznamKlientov extends javax.swing.JFrame {

    private final KlientTableModel klientTableModel = new KlientTableModel();
    private Klient vybranyKlient;

    /**
     * Creates new form JFListOfUsers
     */
    public JFZoznamKlientov() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHladaj = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTZoznamKlientov = new javax.swing.JTable();
        btnVymaz = new javax.swing.JButton();
        btnUprav = new javax.swing.JButton();
        btnZobraz = new javax.swing.JButton();
        btnPocitajUver = new javax.swing.JButton();
        btnSpravujUvery = new javax.swing.JButton();
        btnKoniec = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblHladaj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblHladajKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lblHladajKeyTyped(evt);
            }
        });

        jTZoznamKlientov.setModel(klientTableModel);
        jTZoznamKlientov.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTZoznamKlientov.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTZoznamKlientovMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTZoznamKlientov);

        btnVymaz.setText("Vymaž");
        btnVymaz.setEnabled(false);
        btnVymaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVymazActionPerformed(evt);
            }
        });

        btnUprav.setText("Uprav");
        btnUprav.setEnabled(false);

        btnZobraz.setText("Zobraz");
        btnZobraz.setEnabled(false);
        btnZobraz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZobrazActionPerformed(evt);
            }
        });

        btnPocitajUver.setText("Počítaj úver");
        btnPocitajUver.setEnabled(false);
        btnPocitajUver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPocitajUverActionPerformed(evt);
            }
        });

        btnSpravujUvery.setText("Spravuj úvery");
        btnSpravujUvery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpravujUveryActionPerformed(evt);
            }
        });

        btnKoniec.setText("Koniec");
        btnKoniec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKoniecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHladaj, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnZobraz)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUprav)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVymaz)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPocitajUver)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSpravujUvery)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnKoniec)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHladaj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVymaz)
                    .addComponent(btnUprav)
                    .addComponent(btnZobraz)
                    .addComponent(btnPocitajUver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSpravujUvery)
                    .addComponent(btnKoniec))
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTZoznamKlientovMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTZoznamKlientovMouseClicked
        int riadok = jTZoznamKlientov.getSelectedRow();
        int index = jTZoznamKlientov.convertRowIndexToModel(riadok);
        vybranyKlient = klientTableModel.getKlient(index);
        enableButtons();

        if (evt.getClickCount() == 2) {
            zobrazKlientInfo();
        }
    }//GEN-LAST:event_jTZoznamKlientovMouseClicked

    private void btnVymazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVymazActionPerformed
        klientTableModel.zmaz(vybranyKlient);
        vybranyKlient = null;
        disableButtons();
    }//GEN-LAST:event_btnVymazActionPerformed

    private void btnZobrazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZobrazActionPerformed
        JDKlientInfo jDKlientInfo = new JDKlientInfo(this, vybranyKlient);
        jDKlientInfo.setVisible(true);
    }//GEN-LAST:event_btnZobrazActionPerformed

    private void btnKoniecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKoniecActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnKoniecActionPerformed

    private void btnPocitajUverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPocitajUverActionPerformed
        JDVypocitajUver jDVypocitajUver = new JDVypocitajUver(this, true);
        jDVypocitajUver.setVisible(true);
    }//GEN-LAST:event_btnPocitajUverActionPerformed

    private void lblHladajKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblHladajKeyTyped
        String hladanyTex = lblHladaj.getText();
        hladajKlienta(hladanyTex);
    }//GEN-LAST:event_lblHladajKeyTyped

    private void lblHladajKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblHladajKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getKeyCode() == KeyEvent.VK_DELETE) {
            String hladanyTex = lblHladaj.getText();
            hladajKlienta(hladanyTex);
        }
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            lblHladaj.setText("");
            hladajKlienta("");
        }
    }//GEN-LAST:event_lblHladajKeyReleased

    private void btnSpravujUveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpravujUveryActionPerformed
        JDSpravujUvery jDSpravujUvery = new JDSpravujUvery(this, true);
        jDSpravujUvery.setVisible(true);
    }//GEN-LAST:event_btnSpravujUveryActionPerformed

    private void hladajKlienta(String hladanyText) {
        klientTableModel.hladaj(hladanyText);
    }

    private void zobrazKlientInfo() {
        JDKlientInfo klientInfo = new JDKlientInfo(this, vybranyKlient);
        klientInfo.setVisible(true);
    }

    private void disableButtons() {
        this.btnUprav.setEnabled(false);
        this.btnVymaz.setEnabled(false);
        this.btnZobraz.setEnabled(false);
        this.btnPocitajUver.setEnabled(false);
    }

    private void enableButtons() {
        this.btnUprav.setEnabled(true);
        this.btnVymaz.setEnabled(true);
        this.btnZobraz.setEnabled(true);
        this.btnPocitajUver.setEnabled(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFZoznamKlientov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFZoznamKlientov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFZoznamKlientov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFZoznamKlientov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFZoznamKlientov().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKoniec;
    private javax.swing.JButton btnPocitajUver;
    private javax.swing.JButton btnSpravujUvery;
    private javax.swing.JButton btnUprav;
    private javax.swing.JButton btnVymaz;
    private javax.swing.JButton btnZobraz;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTZoznamKlientov;
    private javax.swing.JTextField lblHladaj;
    // End of variables declaration//GEN-END:variables
}
