package sk.upjs.ics.swib.gui;

import java.math.BigDecimal;
import sk.upjs.ics.swib.entity.Bonus;
import sk.upjs.ics.swib.entity.Multiplikator;
import sk.upjs.ics.swib.entity.Porovnavac;
import sk.upjs.ics.swib.entity.Uver;

/**
 *
 * @author Johnny
 */
public class JDPodmineka extends javax.swing.JDialog {
    
    private MultiplicatorComboBoxModel multiplicatorComboBoxModel = new MultiplicatorComboBoxModel();
    private PorovnavacComboBoxModel porovnavacComboBoxModel = new PorovnavacComboBoxModel();
    private BonusListModel bonusListModel;
    private Uver uver;
    private Bonus bonus;
    
    private String nazov = null;
    private BigDecimal vacsiAko;
    private BigDecimal vyska;
    private int multiplikator;
    private int porovnavac;

    public JDPodmineka(java.awt.Frame parent, Uver uver, Bonus bonus) {
        this(parent, true);
        this.nazov = bonus.getNazov();
        this.vacsiAko = bonus.getJeVacsiAko();
        this.vyska = bonus.getKolkoJeBonus();
        this.multiplikator = bonus.getMultiplikatorId();
        this.porovnavac = bonus.getPorovnavacId();        
        this.uver = uver;
        this.bonusListModel = new BonusListModel(uver);
        
        //System.out.println(nazov+" "+multiplikator+" "+porovnavac);
        
        if (nazov != null){
            jtfNazov.setText(nazov);
            jftfVacsiAko.setText(vacsiAko.toString());
            jftfVyskaBonusu.setText(vyska.toString());
            jcombMultiplikator.setSelectedIndex(multiplikator-1);
            jcombPorovnavac.setSelectedIndex(porovnavac-1);
        }                
    }      

    public JDPodmineka(java.awt.Frame parent, Uver uver) {
        this(parent, true);
        this.uver = uver;
        this.bonusListModel = new BonusListModel(uver);
    }        
    
    public JDPodmineka(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jcombMultiplikator.setModel(multiplicatorComboBoxModel);
        jcombPorovnavac.setModel(porovnavacComboBoxModel);                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfNazov = new javax.swing.JTextField();
        jftfVacsiAko = new javax.swing.JFormattedTextField();
        lblNazov = new javax.swing.JLabel();
        lblVacsiAko = new javax.swing.JLabel();
        jftfVyskaBonusu = new javax.swing.JFormattedTextField();
        lblVyskaBonusu = new javax.swing.JLabel();
        jcombMultiplikator = new javax.swing.JComboBox();
        lblMultiplikator = new javax.swing.JLabel();
        jcombPorovnavac = new javax.swing.JComboBox();
        lblPorovnavac = new javax.swing.JLabel();
        btnUloz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(213, 259));

        jtfNazov.setToolTipText("Názov");

        jftfVacsiAko.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jftfVacsiAko.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jftfVacsiAko.setText("0");

        lblNazov.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNazov.setText("Názov:");

        lblVacsiAko.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblVacsiAko.setText("Väčší ako:");

        jftfVyskaBonusu.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jftfVyskaBonusu.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jftfVyskaBonusu.setText("0");

        lblVyskaBonusu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblVyskaBonusu.setText("Výška bonusu:");

        jcombMultiplikator.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblMultiplikator.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMultiplikator.setText("Multiplikátor:");

        jcombPorovnavac.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblPorovnavac.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPorovnavac.setText("Porovnávač:");

        btnUloz.setText("Ulož");
        btnUloz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUlozActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNazov)
                        .addGap(53, 53, 53)
                        .addComponent(jtfNazov))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVacsiAko)
                            .addComponent(lblVyskaBonusu)
                            .addComponent(lblMultiplikator)
                            .addComponent(lblPorovnavac))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcombPorovnavac, javax.swing.GroupLayout.Alignment.TRAILING, 0, 134, Short.MAX_VALUE)
                            .addComponent(jcombMultiplikator, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jftfVyskaBonusu, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jftfVacsiAko, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUloz)
                .addGap(91, 91, 91))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfNazov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNazov))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jftfVacsiAko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVacsiAko))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jftfVyskaBonusu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVyskaBonusu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcombMultiplikator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMultiplikator))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcombPorovnavac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPorovnavac))
                .addGap(18, 18, 18)
                .addComponent(btnUloz)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUlozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUlozActionPerformed
        String novyNazov = jtfNazov.getText();
        BigDecimal novyJeVacsiAko = new BigDecimal(jftfVacsiAko.getText());
        BigDecimal novaVyskaBonusu = new BigDecimal(jftfVyskaBonusu.getText());
        Multiplikator novyM = multiplicatorComboBoxModel.getMultiplikator(jcombMultiplikator.getSelectedIndex());
        Porovnavac novyP = porovnavacComboBoxModel.getPorovnavac(jcombPorovnavac.getSelectedIndex());
        
        if (bonus == null){
            Bonus novyBonus = new Bonus();
            bonus.setNazov(novyNazov);
            bonus.setJeVacsiAko(novyJeVacsiAko);
            bonus.setKolkoJeBonus(novaVyskaBonusu);
            bonus.setMultiplikatorId(novyM.getId());
            bonus.setPorovnavacId(novyP.getId());
            bonus.setOrderNumber(0);
            bonusListModel.pirdajBonus(bonus);
        }
    }//GEN-LAST:event_btnUlozActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDPodmineka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDPodmineka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDPodmineka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDPodmineka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDPodmineka dialog = new JDPodmineka(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUloz;
    private javax.swing.JComboBox jcombMultiplikator;
    private javax.swing.JComboBox jcombPorovnavac;
    private javax.swing.JFormattedTextField jftfVacsiAko;
    private javax.swing.JFormattedTextField jftfVyskaBonusu;
    private javax.swing.JTextField jtfNazov;
    private javax.swing.JLabel lblMultiplikator;
    private javax.swing.JLabel lblNazov;
    private javax.swing.JLabel lblPorovnavac;
    private javax.swing.JLabel lblVacsiAko;
    private javax.swing.JLabel lblVyskaBonusu;
    // End of variables declaration//GEN-END:variables
}
