package sk.upjs.ics.swib.gui;

/**
 *
 * @author Johnny
 */
public class JDVypocitajUver extends javax.swing.JDialog {
    UverComboBoxModel uverComboBoxModel = new UverComboBoxModel();
    private String vybranyUver = null;
    
    /**
     * Creates new form JDVypocitajUver
     * @param parent
     */
    public JDVypocitajUver(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jcombZoznamUverov.setModel(uverComboBoxModel);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfSuma = new javax.swing.JTextField();
        jtfPocetMesiacov = new javax.swing.JTextField();
        btnPocitaj = new javax.swing.JButton();
        btnStorno = new javax.swing.JButton();
        lblVyskaInychNakladov = new javax.swing.JLabel();
        jtfVyskaInychNakladov = new javax.swing.JTextField();
        lblVyskaUveru = new javax.swing.JLabel();
        lblPocetMesiacov = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaInfo = new javax.swing.JTextArea();
        jcbManzelka = new javax.swing.JCheckBox();
        lblPocetDeti = new javax.swing.JLabel();
        jtfPMPU = new javax.swing.JTextField();
        jtfPMP = new javax.swing.JTextField();
        jtfPMZ = new javax.swing.JTextField();
        lblPMPU = new javax.swing.JLabel();
        lblPMP = new javax.swing.JLabel();
        lblPMZ = new javax.swing.JLabel();
        jcombZoznamUverov = new javax.swing.JComboBox();
        jspPocetDeti = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jtfSuma.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfSuma.setText("0");

        jtfPocetMesiacov.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfPocetMesiacov.setText("0");

        btnPocitaj.setText("Počítaj");
        btnPocitaj.setEnabled(false);

        btnStorno.setText("Storno");
        btnStorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStornoActionPerformed(evt);
            }
        });

        lblVyskaInychNakladov.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblVyskaInychNakladov.setText("Výška iných nákladov (mesačne):");

        jtfVyskaInychNakladov.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfVyskaInychNakladov.setText("0");

        lblVyskaUveru.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblVyskaUveru.setText("Výška úveru:");

        lblPocetMesiacov.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPocetMesiacov.setText("Počet mesiacov:");

        jtaInfo.setColumns(20);
        jtaInfo.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jtaInfo.setRows(5);
        jtaInfo.setEnabled(false);
        jScrollPane1.setViewportView(jtaInfo);

        jcbManzelka.setText("Manželka");

        lblPocetDeti.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPocetDeti.setText("Počet detí:");

        jtfPMPU.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfPMPU.setText("0");
        jtfPMPU.setEnabled(false);

        jtfPMP.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfPMP.setText("0");
        jtfPMP.setEnabled(false);

        jtfPMZ.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfPMZ.setText("0");
        jtfPMZ.setEnabled(false);

        lblPMPU.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPMPU.setText("Priemerná mesačná bilancia:");

        lblPMP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPMP.setText("Priemerný mesačný príjem:");

        lblPMZ.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPMZ.setText("Priemerný meačný zostatok:");

        jcombZoznamUverov.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcombZoznamUverov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcombZoznamUverovActionPerformed(evt);
            }
        });

        jspPocetDeti.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblVyskaInychNakladov)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfVyskaInychNakladov, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblPMZ)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jcbManzelka)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblPMPU)
                                        .addComponent(lblPMP)))
                                .addGap(5, 5, 5)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnPocitaj)
                                .addGap(5, 5, 5)
                                .addComponent(btnStorno))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblPocetDeti)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jspPocetDeti, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))
                            .addComponent(jtfPMPU, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfPMP, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfPMZ, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblVyskaUveru)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblPocetMesiacov)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtfPocetMesiacov, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jcombZoznamUverov, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVyskaInychNakladov)
                    .addComponent(jtfVyskaInychNakladov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPocetDeti)
                    .addComponent(jcbManzelka)
                    .addComponent(jspPocetDeti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcombZoznamUverov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVyskaUveru)
                    .addComponent(jtfSuma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPocetMesiacov)
                    .addComponent(jtfPocetMesiacov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPMPU)
                            .addComponent(jtfPMPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPMP)
                            .addComponent(jtfPMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfPMZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPMZ))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPocitaj)
                            .addComponent(btnStorno)))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStornoActionPerformed
        dispose();
    }//GEN-LAST:event_btnStornoActionPerformed

    private void jcombZoznamUverovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcombZoznamUverovActionPerformed
        vybranyUver = uverComboBoxModel.getElementAt(jcombZoznamUverov.getSelectedIndex());
        if (vybranyUver != null){
            btnPocitaj.setEnabled(true);
        }
    }//GEN-LAST:event_jcombZoznamUverovActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDVypocitajUver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDVypocitajUver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDVypocitajUver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDVypocitajUver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDVypocitajUver dialog = new JDVypocitajUver(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPocitaj;
    private javax.swing.JButton btnStorno;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jcbManzelka;
    private javax.swing.JComboBox jcombZoznamUverov;
    private javax.swing.JSpinner jspPocetDeti;
    private javax.swing.JTextArea jtaInfo;
    private javax.swing.JTextField jtfPMP;
    private javax.swing.JTextField jtfPMPU;
    private javax.swing.JTextField jtfPMZ;
    private javax.swing.JTextField jtfPocetMesiacov;
    private javax.swing.JTextField jtfSuma;
    private javax.swing.JTextField jtfVyskaInychNakladov;
    private javax.swing.JLabel lblPMP;
    private javax.swing.JLabel lblPMPU;
    private javax.swing.JLabel lblPMZ;
    private javax.swing.JLabel lblPocetDeti;
    private javax.swing.JLabel lblPocetMesiacov;
    private javax.swing.JLabel lblVyskaInychNakladov;
    private javax.swing.JLabel lblVyskaUveru;
    // End of variables declaration//GEN-END:variables
}
